server:
  port: 8001
spring:
  application:
    name: short-link-project
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yml
  #  datasource:
  #    username: root
  #    password: 123456
  #    url: jdbc:mysql://127.0.0.1:3306/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
  #      connection-test-query: select 1
  #      connection-timeout: 20000
  #      idle-timeout: 300000
  #      maximum-pool-size: 5
  #      minimum-idle: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 6bcea25e49d09a5d9544c967b57a5ab3
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
    group: short-link_project-service_stats-save_pg_flyday
    topic: short-link_project-service_topic_flyday
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg_flyday
mybatis-plus:
  #  global-config:
  #    db-config:
  #      logic-delete-field: is_deleted //与实体类逻辑删除字段的注解二选一
  #      logic-delete-value: 1  //删除 默认
  #      logic-not-delete-value: 0  //未删除 默认
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


